#!/usr/bin/python

import pywapi

# Get the current conditions for the given station.
noaa = pywapi.get_weather_from_noaa('KARR')
yahoo = pywapi.get_weather_from_yahoo('60502', '')

# The Yahoo pressure dictionary.
ypressure = {'0': 'steady', '1': 'rising', '2': 'falling'}

# This is the list of output lines.
out = []

# Go through the dictionaries and construct a list of the desired output lines.
# out.append('Last update:' + noaa['observation_time'].split(',')[1])
out.append('Sunlight: %s to %s' % (yahoo['astronomy']['sunrise'], yahoo['astronomy']['sunset']))
out.append(yahoo['condition']['text'])
try:
  gust = ', gusting to %s mph' % noaa['wind_gust_mph']
except KeyError:
  gust = ''
out.append('Wind: %s at %s mph%s' % ( noaa['wind_dir'], noaa['wind_mph'], gust))
out.append('Relative Humidity: %s%%' % noaa['relative_humidity'])
out.append('Pressure: %2.2f and %s' % (float(yahoo['atmosphere']['pressure']), ypressure[yahoo['atmosphere']['rising']]))
try:
  out.append('Wind Chill: %s F' % noaa['windchill_f'])
except KeyError:
  pass
try:
  out.append('Heat Index: %s F' % noaa['heat_index_f'])
except KeyError:
  pass
out.append('Temperature: %s F' % noaa['temp_f'])


print '\n'.join(out)
